services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/.env.development
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env.development
    volumes:
      - url_minifier_dev_data:/var/lib/postgresql/data

volumes:
  url_minifier_dev_data:
