services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - url_minifier_data:/var/lib/postgresql/data

volumes:
  url_minifier_data:
