FROM denoland/deno:debian-2.4.3

# Install OpenSSL (required by Prisma)
RUN apt-get update -y && apt-get install -y openssl

# Set working directory inside the container
WORKDIR /app

# Copy dependency manifests from parent folder
COPY deno.json deno.lock ./

# Copy backend source code into image
COPY ./src ./src
COPY ./prisma ./prisma

# Install dependencies
RUN deno install --allow-scripts

# Copy and run the entrypoint script
COPY ./entrypoint.dev.sh ./entrypoint.dev.sh
RUN chmod +x ./entrypoint.dev.sh

# Expose the port of your application
EXPOSE 5000

# Start with entrypoint (will run prisma migrate)
ENTRYPOINT ["./entrypoint.dev.sh"]
